server:
  jetty:
    threads:
      max: 200
      min: 10
  port: 8080
  servlet:
    context-path: /trcode-api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:5000/trcode?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: abc123456
      min-idle: 8
      max-active: 16
      initial-size: 8
      test-on-borrow: true

  redis:
    database: 0
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        min-idle: 8
        max-idle: 16

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.trcode.api.pojo
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

wx:
  app-id: 
  app-secret: 
